### ISSUE TITLE
[HU2] Aficionado del fútbol apostador-2

### ISSUE THREAD

**Issue by sorozcov** [sorozcov/proyecto-iv-ugr#6]
Como este tipo de usuario, quiero conocer la mejor posible apuesta que puedo hacer en los juegos del siguiente fin de semana. Quiero obtener las mejores recomendaciones de apuesta para dichos partidos de forma de lista ordenado por apuesta más segura (apuesta con mayor posibilidad de ganancia y con mayor probabalidad de suceder).

**Comment by JJ** [comment]
En ese caso, #5 sería simplemente un "dado que" o contexto que permitiría seleccionar una apuesta más segura. ¿O se trata de diferentes opciones? También puede ser un "o si no"; si no hay predicciones sobre apuestas seguras fiables, se muestran estadísticas. En todo caso, estarían dentro de la misma HU.
Y por supuesto no tiene sentido que no estén en ningún milestone.

**Comment by sorozcov** [comment]
Esta opción es diferente al #5 ya que el usuario selecciona una serie de partidos o ya bien un solo partido y se generan varias apuestas posibles que son comparadas para que el usuario pueda ver cuales apuestas tienen mejores ganancias y con mayores probabilidades de suceder según nuestro algoritmo. Las "apuestas seguras fiables" no existen, solo existirá un porcentaje que será la apuesta con la que podría ganar más dinero y al mismo tiempo tener mayor porbabilidad de suceder.

**Comment by JJ** [comment]
Sigo pensando que son simplemente dos soluciones posibles al mismo problema, que es apostar con seguridad. Pueden estar en dos hitos diferentes, eso sí.

**Comment by sorozcov** [comment]
Se ha funciona la historia de usuario 2 con la historia de usuario 1, #6 con #5  dado que resuelven el mismo problema apostar seguramente de diferente forma.
