### ISSUE TITLE
[HU-P1] Representar un Partido

### ISSUE THREAD

**Issue by gomares** [sorozcov/proyecto-iv-ugr#9]
Con el objetivo de avanzar en el M0 y teniendo en cuenta la HU1 #5 necesitamos dar una representación y estructura a los partidos de fútbol. Como programador, considero que una posible representación de un partido debe contener los siguientes tipos:

- Equipos -> Vector que contiene los nombres de los equipos.
- Apuestas -> Vector que contiene las apuestas marcadas por el apostador, con sus valores seleccionados.
- Fecha-> Objeto Fecha
- Mejor_apuesta-> Objeto clase Apuesta. Forma parte de la lógica de negocio.

El diseño de Apuestas requiere de otro issue ya que es otra clase.

**Comment by gomares** [comment]
Linkea este issue al primer Milestone por favor :)

**Comment by sorozcov** [comment]
Me parece bien para #5 .

**Comment by JJ** [comment]
El problema de la clase Partido no es "El problema de la clase partido". Es el problema que tienes que resolver, que necesitará una clase, o dos, o *n*. Si presupones que es una sola clase, y que se va a llamar `Partido`, ¿de qué forma estás planteando el problema y ayudando a resolverlo? 
¿Queréis intentar, por favor, tratar de entender lo que se pide en vez de leer "un issue tiene que plantera un problema" y poner en el issue "El problema x"?

**Comment by gomares** [comment]
@sorozcov Tengo una duda que se me plantea, en #5 hablabas de conocer la mejor posible apuesta que puedo hacer en los juegos. Mi pregunta es si ves útil incluir un atributo que contenga la mejor apuesta que sería calculada por tu algoritmo de recomendación o en realidad no es necesario dicho atributo.

**Comment by sorozcov** [comment]
> @sorozcov Tengo una duda que se me plantea, en #5 hablabas de conocer la mejor posible apuesta que puedo hacer en los juegos. Mi pregunta es si ves útil incluir un atributo que contenga la mejor apuesta que sería calculada por tu algoritmo de recomendación o en realidad no es necesario dicho atributo.

Si, me parece bien ya será útil tanto conocerla en cada partido como utilizarla para comparar la mejor apuesta de diferentes partidos cuando al usuario no le importa el equipo como se menciona en #5.

**Comment by gomares** [comment]
Ya está todo por mi parte, revísalo y si quieres lo mandamos a revisión. Creo haber cubierto toda la historia de usuario #5 . @sorozcov .
